# Generated by Django 4.0.4 on 2022-05-31 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Image',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
