# Generated by Django 4.0.4 on 2022-06-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Quantity',
            field=models.CharField(max_length=50),
        ),
    ]
