# Generated by Django 4.0.4 on 2022-06-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Postno', models.CharField(max_length=10)),
                ('Image', models.ImageField(upload_to='img/')),
                ('Itemname', models.CharField(max_length=1000)),
            ],
        ),
    ]
