# Generated by Django 4.0.4 on 2022-06-01 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='Itemname',
            new_name='Postdetails',
        ),
    ]
