# Generated by Django 4.0.4 on 2022-06-02 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_rename_itemname_posts_postdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeafUser',
        ),
    ]
