# Generated by Django 4.0.4 on 2022-06-04 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_leafuser_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeafUser',
            new_name='User',
        ),
    ]
