# Generated by Django 4.0.4 on 2022-06-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0014_delete_item_delete_posts_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Itemname', models.CharField(max_length=50)),
                ('Price', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Postno', models.CharField(max_length=10)),
                ('Image', models.ImageField(upload_to='img/')),
                ('Postdetails', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Servicetype', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=50)),
                ('Phonenumber', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Confirmpassword', models.CharField(max_length=50)),
            ],
        ),
    ]
